version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: accountability-framework-system-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prismapass
      POSTGRES_DB: accountability_framework_system
    volumes:
      - accountability_framework_system_db:/var/lib/postgresql/data

volumes:
  accountability_framework_system_db: