var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/responsibility-management/description/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__742c0a78._.js")
R.c("server/chunks/ssr/3d567_next_dist_esm_server_lib_patch-fetch_88ca857e.js")
R.c("server/chunks/ssr/node_modules__pnpm_f1d07464._.js")
R.c("server/chunks/ssr/3d567_next_dist_89ecc763._.js")
R.c("server/chunks/ssr/app_0ef037c1._.js")
R.c("server/chunks/ssr/[root-of-the-server]__b27ff96e._.js")
R.c("server/chunks/ssr/3d567_next_dist_client_components_275f07d0._.js")
R.c("server/chunks/ssr/3d567_next_dist_client_components_builtin_forbidden_fd9a226c.js")
R.c("server/chunks/ssr/3d567_next_dist_client_components_builtin_unauthorized_3c96e4ee.js")
R.c("server/chunks/ssr/3d567_next_dist_client_components_builtin_global-error_e8b4591b.js")
R.c("server/chunks/ssr/app_responsibility-management_layout_tsx_f8d448ad._.js")
R.c("server/chunks/ssr/[root-of-the-server]__c60554bb._.js")
R.c("server/chunks/ssr/_dac0da2c._.js")
R.c("server/chunks/ssr/_41fcdedf._.js")
R.m(80672)
R.m(91400)
module.exports=R.m(91400).exports
